/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    articles: Article;
    sections: Section;
    regions: Region;
    authors: Author;
    media: Media;
    users: User;
    'share-links': ShareLink;
    'live-blogs': LiveBlog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    sections: SectionsSelect<false> | SectionsSelect<true>;
    regions: RegionsSelect<false> | RegionsSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'share-links': ShareLinksSelect<false> | ShareLinksSelect<true>;
    'live-blogs': LiveBlogsSelect<false> | LiveBlogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Globdot global news articles, analysis, and feature stories.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * Auto-generated from title.
   */
  slug?: string | null;
  /**
   * Lead summary paragraph
   */
  standfirst: string;
  /**
   * Private verified facts, quotations, source excerpts, and context used by the drafting assistant. Never paste unsupported claims.
   */
  reportingNotes?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverImage?: (number | null) | Media;
  /**
   * Direct links to primary documents or reporting used for this article.
   */
  sourceLinks?:
    | {
        name: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  section: number | Section;
  /**
   * Geographic relevance
   */
  regions?: (number | Region)[] | null;
  author: number | Author;
  /**
   * e.g. NAIROBI, GENEVA, SUVA
   */
  dateline?: string | null;
  /**
   * Controls the article presentation and AI drafting structure.
   */
  storyType?: ('news' | 'analysis' | 'explainer' | 'opinion' | 'interview' | 'video') | null;
  status?: ('draft' | 'in_review' | 'approved' | 'published' | 'archived') | null;
  homepageSlot?: ('standard' | 'lead' | 'secondary' | 'editors_pick') | null;
  isBreaking?: boolean | null;
  isFeatured?: boolean | null;
  publishedAt?: string | null;
  /**
   * Auto-calculated
   */
  readTime?: number | null;
  viewCount?: number | null;
  /**
   * Editorial correction or clarification note
   */
  correctionNote?: string | null;
  /**
   * Every item must be true and accurate before publication.
   */
  editorialReview?: {
    factChecked?: boolean | null;
    sourcesChecked?: boolean | null;
    imageRightsChecked?: boolean | null;
    reviewedBy?: string | null;
    reviewedAt?: string | null;
  };
  og?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Images and multimedia assets for articles.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alt text for accessibility and SEO
   */
  alt?: string | null;
  /**
   * Optional caption displayed below image
   */
  caption?: string | null;
  /**
   * Photo attribution (e.g. Globdot / Reuters / AP)
   */
  credit?: string | null;
  source?: ('local' | 'external') | null;
  /**
   * Direct link to an external image
   */
  externalUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Editorial desks / channels (World, Politics, Climate, etc.)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections".
 */
export interface Section {
  id: number;
  name: string;
  slug?: string | null;
  description?: string | null;
  color: string;
  sortOrder: number;
  isVisible?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Geographic regions (Africa, Americas, Asia, Europe, Middle East, Oceania)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions".
 */
export interface Region {
  id: number;
  name: string;
  slug?: string | null;
  description?: string | null;
  sortOrder: number;
  isVisible?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Globdot correspondents, contributors, and byline authors.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  slug?: string | null;
  /**
   * e.g. "Senior Climate Correspondent"
   */
  roleTitle?: string | null;
  bio?: string | null;
  avatar?: (number | null) | Media;
  email?: string | null;
  socialUrl?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Globdot newsroom staff with role-based access.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor' | 'writer';
  avatar?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Dynamic tracked shortlinks for campaign and social sharing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "share-links".
 */
export interface ShareLink {
  id: number;
  /**
   * Auto-generated unique short key.
   */
  key?: string | null;
  /**
   * Target article for this share link.
   */
  article: number | Article;
  /**
   * Campaign label (e.g. "Twitter Morning Feed", "Newsletter").
   */
  label?: string | null;
  /**
   * Marketing distribution channel.
   */
  channel?: ('facebook' | 'twitter' | 'telegram' | 'newsletter' | 'other') | null;
  /**
   * Page or campaign identifier (e.g. "fb_page_1", "breaking_wire").
   */
  pageKey?: string | null;
  /**
   * UTM medium (e.g. "comment", "post", "bio").
   */
  utmMedium?: string | null;
  clicks?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Real-time live blogging coverage and rolling updates.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "live-blogs".
 */
export interface LiveBlog {
  id: number;
  title: string;
  slug?: string | null;
  summary: string;
  status?: ('draft' | 'live' | 'ended') | null;
  startedAt?: string | null;
  updates?:
    | {
        headline?: string | null;
        body: string;
        author?: (number | null) | Author;
        isPinned?: boolean | null;
        publishedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'sections';
        value: number | Section;
      } | null)
    | ({
        relationTo: 'regions';
        value: number | Region;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'share-links';
        value: number | ShareLink;
      } | null)
    | ({
        relationTo: 'live-blogs';
        value: number | LiveBlog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  standfirst?: T;
  reportingNotes?: T;
  content?: T;
  coverImage?: T;
  sourceLinks?:
    | T
    | {
        name?: T;
        url?: T;
        id?: T;
      };
  section?: T;
  regions?: T;
  author?: T;
  dateline?: T;
  storyType?: T;
  status?: T;
  homepageSlot?: T;
  isBreaking?: T;
  isFeatured?: T;
  publishedAt?: T;
  readTime?: T;
  viewCount?: T;
  correctionNote?: T;
  editorialReview?:
    | T
    | {
        factChecked?: T;
        sourcesChecked?: T;
        imageRightsChecked?: T;
        reviewedBy?: T;
        reviewedAt?: T;
      };
  og?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections_select".
 */
export interface SectionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  color?: T;
  sortOrder?: T;
  isVisible?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions_select".
 */
export interface RegionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  sortOrder?: T;
  isVisible?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  roleTitle?: T;
  bio?: T;
  avatar?: T;
  email?: T;
  socialUrl?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  source?: T;
  externalUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "share-links_select".
 */
export interface ShareLinksSelect<T extends boolean = true> {
  key?: T;
  article?: T;
  label?: T;
  channel?: T;
  pageKey?: T;
  utmMedium?: T;
  clicks?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "live-blogs_select".
 */
export interface LiveBlogsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  status?: T;
  startedAt?: T;
  updates?:
    | T
    | {
        headline?: T;
        body?: T;
        author?: T;
        isPinned?: T;
        publishedAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}