INSERT OR IGNORE INTO articles
  (id, slug, title, standfirst, body_json, status, story_type, section_id, created_by_id, is_breaking, is_featured, read_time_minutes, dateline, key_points_json, published_at)
VALUES
  (9, 'ocean-warming-redraws-fishing-seasons', 'Ocean warming is redrawing fishing seasons across the Pacific', 'Communities are adapting as familiar species move, spawning periods shift and old calendars become less reliable.', '{"paragraphs":["Fishing communities across the Pacific are recording changes in where and when familiar species appear. Scientists say warmer water is shifting habitats and altering spawning cycles.","Local knowledge remains central to adaptation. Crews are combining generations of observation with satellite forecasts, while regulators reconsider fixed seasons designed for a more stable climate.","The transition carries economic risks for small operators who cannot easily travel farther or replace specialized equipment."],"version":1}', 'published', 'news', 5, 1, 0, 0, 5, 'SUVA', '["Marine habitats are moving","Local knowledge is guiding adaptation","Fixed fishing calendars are becoming less reliable"]', '2026-09-13T23:20:00Z'),
  (10, 'ai-translation-public-services-africa', 'AI translation tools move from experiments into public services', 'New systems promise wider access to government information while raising difficult questions about accuracy.', '{"paragraphs":["Public agencies are testing language models to translate health guidance, legal forms and agricultural information into languages poorly served by commercial software.","Officials say the tools can broaden access, but linguists warn that fluent output can conceal serious errors. Human review remains essential for high-stakes information.","Community groups are asking governments to publish accuracy results and involve native speakers in training and evaluation."],"version":1}', 'published', 'explainer', 4, 1, 0, 0, 5, 'NAIROBI', '["Public services are testing low-resource languages","Fluency does not guarantee accuracy","Communities want a role in evaluation"]', '2026-09-13T22:10:00Z'),
  (11, 'water-treaty-explained', 'The water treaty that could reshape cooperation across three borders', 'A new formula links water releases to rainfall and demand rather than fixed annual quotas.', '{"paragraphs":["The proposed treaty replaces fixed allocations with a formula that changes according to reservoir levels, rainfall and verified agricultural demand.","Supporters say flexibility can reduce conflict during drought. Critics want stronger guarantees for communities downstream and independent monitoring of the data.","The agreement matters beyond the basin because negotiators elsewhere are considering similar climate-adjusted rules."],"version":1}', 'published', 'explainer', 8, 1, 0, 0, 5, 'GENEVA', '["Allocations would respond to conditions","Independent data is central to trust","The model could influence other treaties"]', '2026-09-13T19:30:00Z'),
  (12, 'inside-election-counting-center', 'Inside the election counting center built for transparency', 'Cameras, parallel tallies and public result logs are being used to strengthen confidence in a close vote.', '{"paragraphs":["Our visual report follows ballots from sealed boxes through verification, counting and publication. Each stage leaves a record that observers can compare.","Election officials say transparency must be designed before voting begins. Publishing partial results without context can create confusion even when the count is accurate."],"version":1}', 'published', 'video', 9, 1, 0, 0, 7, 'ACCRA', '["Each counting stage leaves an audit record","Observers run parallel checks","Clear communication is part of election integrity"]', '2026-09-13T18:15:00Z');

INSERT OR IGNORE INTO article_authors (article_id, author_id, position) VALUES (9,3,0),(10,2,0),(11,1,0),(12,4,0);
INSERT OR IGNORE INTO article_regions (article_id, region_id, is_primary) VALUES (9,6,1),(10,1,1),(11,4,1),(11,5,0),(12,1,1);
PRAGMA optimize;
