/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  serial,
  jsonb,
  boolean,
  timestamp,
  numeric,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const enum_articles_cover_display_mode = pgEnum(
  "enum_articles_cover_display_mode",
  ["auto", "ambient", "banner"],
);
export const enum_articles_cover_focal_position = pgEnum(
  "enum_articles_cover_focal_position",
  ["auto", "top", "center", "bottom"],
);
export const enum_articles_story_type = pgEnum("enum_articles_story_type", [
  "news",
  "analysis",
  "explainer",
  "opinion",
  "interview",
  "video",
]);
export const enum_articles_status = pgEnum("enum_articles_status", [
  "draft",
  "in_review",
  "approved",
  "published",
  "archived",
]);
export const enum_articles_homepage_slot = pgEnum(
  "enum_articles_homepage_slot",
  ["standard", "lead", "secondary", "editors_pick"],
);
export const enum_media_source = pgEnum("enum_media_source", [
  "local",
  "external",
]);
export const enum_media_focal_position = pgEnum("enum_media_focal_position", [
  "top",
  "center",
  "bottom",
]);
export const enum_users_role = pgEnum("enum_users_role", [
  "admin",
  "editor",
  "writer",
]);
export const enum_share_links_channel = pgEnum("enum_share_links_channel", [
  "facebook",
  "twitter",
  "telegram",
  "newsletter",
  "other",
]);
export const enum_live_blogs_status = pgEnum("enum_live_blogs_status", [
  "draft",
  "live",
  "ended",
]);

export const articles_source_links = pgTable(
  "articles_source_links",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    name: varchar("name").notNull(),
    url: varchar("url").notNull(),
  },
  (columns) => [
    index("articles_source_links_order_idx").on(columns._order),
    index("articles_source_links_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [articles.id],
      name: "articles_source_links_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const articles = pgTable(
  "articles",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    slug: varchar("slug"),
    standfirst: varchar("standfirst").notNull(),
    reportingNotes: varchar("reporting_notes"),
    content: jsonb("content"),
    coverImage: integer("cover_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    coverDisplayMode:
      enum_articles_cover_display_mode("cover_display_mode").default("auto"),
    coverFocalPosition: enum_articles_cover_focal_position(
      "cover_focal_position",
    ).default("auto"),
    section: integer("section_id")
      .notNull()
      .references(() => sections.id, {
        onDelete: "set null",
      }),
    author: integer("author_id")
      .notNull()
      .references(() => authors.id, {
        onDelete: "set null",
      }),
    dateline: varchar("dateline"),
    storyType: enum_articles_story_type("story_type").default("news"),
    status: enum_articles_status("status").default("published"),
    homepageSlot:
      enum_articles_homepage_slot("homepage_slot").default("standard"),
    isBreaking: boolean("is_breaking").default(false),
    isFeatured: boolean("is_featured").default(false),
    publishedAt: timestamp("published_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    readTime: numeric("read_time", { mode: "number" }),
    viewCount: numeric("view_count", { mode: "number" }).default(0),
    correctionNote: varchar("correction_note"),
    editorialReview_factChecked: boolean("editorial_review_fact_checked"),
    editorialReview_sourcesChecked: boolean("editorial_review_sources_checked"),
    editorialReview_imageRightsChecked: boolean(
      "editorial_review_image_rights_checked",
    ),
    editorialReview_reviewedBy: varchar("editorial_review_reviewed_by"),
    editorialReview_reviewedAt: timestamp("editorial_review_reviewed_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    og_metaTitle: varchar("og_meta_title"),
    og_metaDescription: varchar("og_meta_description"),
    og_ogImage: integer("og_og_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    meta_title: varchar("meta_title"),
    meta_description: varchar("meta_description"),
    meta_image: integer("meta_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("articles_slug_idx").on(columns.slug),
    index("articles_cover_image_idx").on(columns.coverImage),
    index("articles_section_idx").on(columns.section),
    index("articles_author_idx").on(columns.author),
    index("articles_og_og_og_image_idx").on(columns.og_ogImage),
    index("articles_meta_meta_image_idx").on(columns.meta_image),
    index("articles_updated_at_idx").on(columns.updatedAt),
    index("articles_created_at_idx").on(columns.createdAt),
  ],
);

export const articles_rels = pgTable(
  "articles_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    regionsID: integer("regions_id"),
  },
  (columns) => [
    index("articles_rels_order_idx").on(columns.order),
    index("articles_rels_parent_idx").on(columns.parent),
    index("articles_rels_path_idx").on(columns.path),
    index("articles_rels_regions_id_idx").on(columns.regionsID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [articles.id],
      name: "articles_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["regionsID"]],
      foreignColumns: [regions.id],
      name: "articles_rels_regions_fk",
    }).onDelete("cascade"),
  ],
);

export const sections = pgTable(
  "sections",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    slug: varchar("slug"),
    description: varchar("description"),
    color: varchar("color").notNull().default("#2457ff"),
    sortOrder: numeric("sort_order", { mode: "number" }).notNull().default(0),
    isVisible: boolean("is_visible").default(true),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("sections_slug_idx").on(columns.slug),
    index("sections_updated_at_idx").on(columns.updatedAt),
    index("sections_created_at_idx").on(columns.createdAt),
  ],
);

export const regions = pgTable(
  "regions",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    slug: varchar("slug"),
    description: varchar("description"),
    sortOrder: numeric("sort_order", { mode: "number" }).notNull().default(0),
    isVisible: boolean("is_visible").default(true),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("regions_slug_idx").on(columns.slug),
    index("regions_updated_at_idx").on(columns.updatedAt),
    index("regions_created_at_idx").on(columns.createdAt),
  ],
);

export const authors = pgTable(
  "authors",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    slug: varchar("slug"),
    roleTitle: varchar("role_title"),
    bio: varchar("bio"),
    avatar: integer("avatar_id").references(() => media.id, {
      onDelete: "set null",
    }),
    email: varchar("email"),
    socialUrl: varchar("social_url"),
    isActive: boolean("is_active").default(true),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("authors_slug_idx").on(columns.slug),
    index("authors_avatar_idx").on(columns.avatar),
    index("authors_updated_at_idx").on(columns.updatedAt),
    index("authors_created_at_idx").on(columns.createdAt),
  ],
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt").default("Globdot reporting"),
    caption: varchar("caption"),
    credit: varchar("credit"),
    source: enum_media_source("source").default("local"),
    focalPosition: enum_media_focal_position("focal_position").default("top"),
    externalUrl: varchar("external_url"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
    sizes_thumbnail_url: varchar("sizes_thumbnail_url"),
    sizes_thumbnail_width: numeric("sizes_thumbnail_width", { mode: "number" }),
    sizes_thumbnail_height: numeric("sizes_thumbnail_height", {
      mode: "number",
    }),
    sizes_thumbnail_mimeType: varchar("sizes_thumbnail_mime_type"),
    sizes_thumbnail_filesize: numeric("sizes_thumbnail_filesize", {
      mode: "number",
    }),
    sizes_thumbnail_filename: varchar("sizes_thumbnail_filename"),
    sizes_card_url: varchar("sizes_card_url"),
    sizes_card_width: numeric("sizes_card_width", { mode: "number" }),
    sizes_card_height: numeric("sizes_card_height", { mode: "number" }),
    sizes_card_mimeType: varchar("sizes_card_mime_type"),
    sizes_card_filesize: numeric("sizes_card_filesize", { mode: "number" }),
    sizes_card_filename: varchar("sizes_card_filename"),
    sizes_hero_url: varchar("sizes_hero_url"),
    sizes_hero_width: numeric("sizes_hero_width", { mode: "number" }),
    sizes_hero_height: numeric("sizes_hero_height", { mode: "number" }),
    sizes_hero_mimeType: varchar("sizes_hero_mime_type"),
    sizes_hero_filesize: numeric("sizes_hero_filesize", { mode: "number" }),
    sizes_hero_filename: varchar("sizes_hero_filename"),
  },
  (columns) => [
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
    index("media_sizes_thumbnail_sizes_thumbnail_filename_idx").on(
      columns.sizes_thumbnail_filename,
    ),
    index("media_sizes_card_sizes_card_filename_idx").on(
      columns.sizes_card_filename,
    ),
    index("media_sizes_hero_sizes_hero_filename_idx").on(
      columns.sizes_hero_filename,
    ),
  ],
);

export const users_sessions = pgTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = pgTable(
  "users",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    role: enum_users_role("role").notNull().default("writer"),
    avatar: integer("avatar_id").references(() => media.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("users_avatar_idx").on(columns.avatar),
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const share_links = pgTable(
  "share_links",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    article: integer("article_id")
      .notNull()
      .references(() => articles.id, {
        onDelete: "set null",
      }),
    label: varchar("label"),
    channel: enum_share_links_channel("channel").default("facebook"),
    pageKey: varchar("page_key"),
    utmMedium: varchar("utm_medium").default("comment"),
    clicks: numeric("clicks", { mode: "number" }).default(0),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("share_links_key_idx").on(columns.key),
    index("share_links_article_idx").on(columns.article),
    index("share_links_updated_at_idx").on(columns.updatedAt),
    index("share_links_created_at_idx").on(columns.createdAt),
  ],
);

export const live_blogs_updates = pgTable(
  "live_blogs_updates",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    headline: varchar("headline"),
    body: varchar("body").notNull(),
    author: integer("author_id").references(() => authors.id, {
      onDelete: "set null",
    }),
    isPinned: boolean("is_pinned").default(false),
    publishedAt: timestamp("published_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("live_blogs_updates_order_idx").on(columns._order),
    index("live_blogs_updates_parent_id_idx").on(columns._parentID),
    index("live_blogs_updates_author_idx").on(columns.author),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [live_blogs.id],
      name: "live_blogs_updates_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const live_blogs = pgTable(
  "live_blogs",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    slug: varchar("slug"),
    summary: varchar("summary").notNull(),
    status: enum_live_blogs_status("status").default("draft"),
    startedAt: timestamp("started_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("live_blogs_slug_idx").on(columns.slug),
    index("live_blogs_updated_at_idx").on(columns.updatedAt),
    index("live_blogs_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_kv = pgTable(
  "payload_kv",
  {
    id: serial("id").primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    articlesID: integer("articles_id"),
    sectionsID: integer("sections_id"),
    regionsID: integer("regions_id"),
    authorsID: integer("authors_id"),
    mediaID: integer("media_id"),
    usersID: integer("users_id"),
    "share-linksID": integer("share_links_id"),
    "live-blogsID": integer("live_blogs_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_articles_id_idx").on(
      columns.articlesID,
    ),
    index("payload_locked_documents_rels_sections_id_idx").on(
      columns.sectionsID,
    ),
    index("payload_locked_documents_rels_regions_id_idx").on(columns.regionsID),
    index("payload_locked_documents_rels_authors_id_idx").on(columns.authorsID),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_share_links_id_idx").on(
      columns["share-linksID"],
    ),
    index("payload_locked_documents_rels_live_blogs_id_idx").on(
      columns["live-blogsID"],
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["articlesID"]],
      foreignColumns: [articles.id],
      name: "payload_locked_documents_rels_articles_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["sectionsID"]],
      foreignColumns: [sections.id],
      name: "payload_locked_documents_rels_sections_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["regionsID"]],
      foreignColumns: [regions.id],
      name: "payload_locked_documents_rels_regions_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["authorsID"]],
      foreignColumns: [authors.id],
      name: "payload_locked_documents_rels_authors_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["share-linksID"]],
      foreignColumns: [share_links.id],
      name: "payload_locked_documents_rels_share_links_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["live-blogsID"]],
      foreignColumns: [live_blogs.id],
      name: "payload_locked_documents_rels_live_blogs_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const relations_articles_source_links = relations(
  articles_source_links,
  ({ one }) => ({
    _parentID: one(articles, {
      fields: [articles_source_links._parentID],
      references: [articles.id],
      relationName: "sourceLinks",
    }),
  }),
);
export const relations_articles_rels = relations(articles_rels, ({ one }) => ({
  parent: one(articles, {
    fields: [articles_rels.parent],
    references: [articles.id],
    relationName: "_rels",
  }),
  regionsID: one(regions, {
    fields: [articles_rels.regionsID],
    references: [regions.id],
    relationName: "regions",
  }),
}));
export const relations_articles = relations(articles, ({ one, many }) => ({
  coverImage: one(media, {
    fields: [articles.coverImage],
    references: [media.id],
    relationName: "coverImage",
  }),
  sourceLinks: many(articles_source_links, {
    relationName: "sourceLinks",
  }),
  section: one(sections, {
    fields: [articles.section],
    references: [sections.id],
    relationName: "section",
  }),
  author: one(authors, {
    fields: [articles.author],
    references: [authors.id],
    relationName: "author",
  }),
  og_ogImage: one(media, {
    fields: [articles.og_ogImage],
    references: [media.id],
    relationName: "og_ogImage",
  }),
  meta_image: one(media, {
    fields: [articles.meta_image],
    references: [media.id],
    relationName: "meta_image",
  }),
  _rels: many(articles_rels, {
    relationName: "_rels",
  }),
}));
export const relations_sections = relations(sections, () => ({}));
export const relations_regions = relations(regions, () => ({}));
export const relations_authors = relations(authors, ({ one }) => ({
  avatar: one(media, {
    fields: [authors.avatar],
    references: [media.id],
    relationName: "avatar",
  }),
}));
export const relations_media = relations(media, () => ({}));
export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ one, many }) => ({
  avatar: one(media, {
    fields: [users.avatar],
    references: [media.id],
    relationName: "avatar",
  }),
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_share_links = relations(share_links, ({ one }) => ({
  article: one(articles, {
    fields: [share_links.article],
    references: [articles.id],
    relationName: "article",
  }),
}));
export const relations_live_blogs_updates = relations(
  live_blogs_updates,
  ({ one }) => ({
    _parentID: one(live_blogs, {
      fields: [live_blogs_updates._parentID],
      references: [live_blogs.id],
      relationName: "updates",
    }),
    author: one(authors, {
      fields: [live_blogs_updates.author],
      references: [authors.id],
      relationName: "author",
    }),
  }),
);
export const relations_live_blogs = relations(live_blogs, ({ many }) => ({
  updates: many(live_blogs_updates, {
    relationName: "updates",
  }),
}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    articlesID: one(articles, {
      fields: [payload_locked_documents_rels.articlesID],
      references: [articles.id],
      relationName: "articles",
    }),
    sectionsID: one(sections, {
      fields: [payload_locked_documents_rels.sectionsID],
      references: [sections.id],
      relationName: "sections",
    }),
    regionsID: one(regions, {
      fields: [payload_locked_documents_rels.regionsID],
      references: [regions.id],
      relationName: "regions",
    }),
    authorsID: one(authors, {
      fields: [payload_locked_documents_rels.authorsID],
      references: [authors.id],
      relationName: "authors",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    "share-linksID": one(share_links, {
      fields: [payload_locked_documents_rels["share-linksID"]],
      references: [share_links.id],
      relationName: "share-links",
    }),
    "live-blogsID": one(live_blogs, {
      fields: [payload_locked_documents_rels["live-blogsID"]],
      references: [live_blogs.id],
      relationName: "live-blogs",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);

type DatabaseSchema = {
  enum_articles_cover_display_mode: typeof enum_articles_cover_display_mode;
  enum_articles_cover_focal_position: typeof enum_articles_cover_focal_position;
  enum_articles_story_type: typeof enum_articles_story_type;
  enum_articles_status: typeof enum_articles_status;
  enum_articles_homepage_slot: typeof enum_articles_homepage_slot;
  enum_media_source: typeof enum_media_source;
  enum_media_focal_position: typeof enum_media_focal_position;
  enum_users_role: typeof enum_users_role;
  enum_share_links_channel: typeof enum_share_links_channel;
  enum_live_blogs_status: typeof enum_live_blogs_status;
  articles_source_links: typeof articles_source_links;
  articles: typeof articles;
  articles_rels: typeof articles_rels;
  sections: typeof sections;
  regions: typeof regions;
  authors: typeof authors;
  media: typeof media;
  users_sessions: typeof users_sessions;
  users: typeof users;
  share_links: typeof share_links;
  live_blogs_updates: typeof live_blogs_updates;
  live_blogs: typeof live_blogs;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  relations_articles_source_links: typeof relations_articles_source_links;
  relations_articles_rels: typeof relations_articles_rels;
  relations_articles: typeof relations_articles;
  relations_sections: typeof relations_sections;
  relations_regions: typeof relations_regions;
  relations_authors: typeof relations_authors;
  relations_media: typeof relations_media;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_share_links: typeof relations_share_links;
  relations_live_blogs_updates: typeof relations_live_blogs_updates;
  relations_live_blogs: typeof relations_live_blogs;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
